sudo: required
language: python

python:
  - "3.6"

services:
  - docker

install:
- pip install -r requirements.txt

script:
- PYTHONPATH=. pytest

after_success:
- docker build -t gpkc/hello_containers_travis:latest .
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push gpkc/hello_containers_travis:latest;
  fi
