version: '3'
services:
  app1:
    build: .
  app2:
    build: .
  nginx:
    image: "nginx:1.13.9"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    links:
      - app1
      - app2